### ISSUE TITLE
Exception in prod

### ISSUE THREAD

**Issue by binrush** [binrush/thousands#36]
```
2015-12-21 10:34:25,890 - thousands - ERROR - Exception on /login/vk [GET]
Traceback (most recent call last):
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/app-root/runtime/repo/thousands/auth.py", line 70, in vk_login
    vk_get_user)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/app-root/runtime/repo/thousands/auth.py", line 87, in oauth_login
    raise AuthError(req.args.get('error_description'))
AuthError: User denied your request
2015-12-21 10:34:32,615 - thousands - INFO - New user registration uid=45, src=1, name=****
2015-12-21 10:34:48,704 - thousands - ERROR - Exception on /login/vk [GET]
Traceback (most recent call last):
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/python/virtenv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/app-root/runtime/repo/thousands/auth.py", line 70, in vk_login
    vk_get_user)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/app-root/runtime/repo/thousands/auth.py", line 94, in oauth_login
    user, created = get_user(credentials)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/app-root/runtime/repo/thousands/auth.py", line 159, in vk_get_user
    user.id = g.users_dao.create(user)
  File "/var/lib/openshift/55d5ae9189f5cfa557000085/app-root/runtime/repo/thousands/dao.py", line 323, in create
    user.preview_id))
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/psycopg2/extras.py", line 120, in execute
    return super(DictCursor, self).execute(query, vars)
IntegrityError: duplicate key value violates unique constraint "users_oauth_id_src_key"
DETAIL:  Key (oauth_id, src)=(1573559, 1) already exists.
```

**Comment by binrush** [comment]
When error occured during oauth process, application raises AuthError. It should redirect back to site with some error message flashed
