### ISSUE TITLE
VK registration broken

### ISSUE THREAD

**Issue by binrush** [binrush/thousands#59]
```
Jul 05 04:25:27 thousands gunicorn[670]: 2018-07-05 04:25:27,984 - thousands - ERROR - Exception on /login/vk [GET]
Jul 05 04:25:27 thousands gunicorn[670]: Traceback (most recent call last):
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
Jul 05 04:25:27 thousands gunicorn[670]:     response = self.full_dispatch_request()
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatc
Jul 05 04:25:27 thousands gunicorn[670]:     rv = self.handle_user_exception(e)
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_
Jul 05 04:25:27 thousands gunicorn[670]:     reraise(exc_type, exc_value, tb)
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatc
Jul 05 04:25:27 thousands gunicorn[670]:     rv = self.dispatch_request()
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_req
Jul 05 04:25:27 thousands gunicorn[670]:     return self.view_functions[rule.endpoint](**req.view_args)
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/thousands/auth.py", line 72, in vk_login
Jul 05 04:25:27 thousands gunicorn[670]:     vk_get_user)
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/thousands/auth.py", line 101, in oauth_lo
Jul 05 04:25:27 thousands gunicorn[670]:     user, created = get_user(credentials)
Jul 05 04:25:27 thousands gunicorn[670]:   File "/opt/thousands/venv/local/lib/python2.7/site-packages/thousands/auth.py", line 157, in vk_get_u
Jul 05 04:25:27 thousands gunicorn[670]:     data = json.loads(content)['response'][0]
Jul 05 04:25:27 thousands gunicorn[670]: KeyError: 'response'
Jul 05 04:25:28 thousands gunicorn[670]: Traceback (most recent call last):
Jul 05 04:25:28 thousands gunicorn[670]:   File "/usr/lib/python2.7/logging/handlers.py", line 942, in emit
Jul 05 04:25:28 thousands gunicorn[670]:     smtp.login(self.username, self.password)
Jul 05 04:25:28 thousands gunicorn[670]:   File "/usr/lib/python2.7/smtplib.py", line 622, in login
Jul 05 04:25:28 thousands gunicorn[670]:     raise SMTPAuthenticationError(code, resp)
Jul 05 04:25:28 thousands gunicorn[670]: SMTPAuthenticationError: (535, '5.7.8 Error: authentication failed: Invalid user or password!')
Jul 05 04:25:28 thousands gunicorn[670]: Logged from file app.py, line 1423
```

**Comment by PavelQuash** [comment]
Не могу зайти по ВК аккаунтом, вылетает пятисотка.
